workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - android_keystore
      vars:
        PACKAGE_NAME: "com.oluwaseun.codemagicdemo"
        BUILD_NUMBER: 3

    scripts:
      - flutter pub get
      - flutter analyze
      - flutter test || true
      - flutter build appbundle --release --build-number=$BUILD_NUMBER

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: "1:314617896266:android:b89eccb9c10d200869b5b3"
          testers:
            - seunagbomola@gmail.com

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT
        track: internal
