workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - my_keystore
      groups:
        - google_cloud_credentials

      vars:
        PACKAGE_NAME: "com.oluwaseun.codemagicdemo"



    scripts:
      - flutter pub get
      - flutter analyze
      - flutter test || true
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release --build-number=$BUILD_NUMBER


    artifacts:
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT
        track: internal
